--게시글 목록
SELECT * FROM NOTICEFILES;
SELECT * FROM NOTICES ORDER BY REGDATE DESC;
--게시글 조회
SELECT * FROM NOTICES WHERE CODE = 135;

--현재 공지사항에서 가장 큰 CODE 얻기
SELECT NVL(MAX(TO_NUMBER(CODE)),0)+1 FROM NOTICES;

--20개씩 나눈 레코드를 얻어오는 쿼리를 작성하시오
--1페이지, 2페이지
SELECT * FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) 
--ROWNUM을 이용한 페이지 나누기
WHERE ROWNUM BETWEEN 1 AND 20 ;

INSERT INTO NOTICES(CODE,TITLE,WRITER,CONTENT,REGDATE,HIT) VALUES('132','eoot','hj','album',SYSDATE,0);

SELECT * FROM (SELECT ROWNUM NUM, N.* FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) N )
WHERE NUM BETWEEN 2 AND 4 ;

SELECT COUNT(CODE) FROM NOTICES;

SELECT N.* FROM 
(SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM, NOTICES.* FROM NOTICES) N
WHERE NUM BETWEEN 11 AND 20 ;

SELECT ISNULL(MAX(CAST(CODE AS INT)),0)+1 FROM NOTICEFILES;

SELECT TOP 1 * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE = '242') ORDER BY REGDATE ASC;
SELECT TOP 1 * FROM NOTICES WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE = '242') ORDER BY REGDATE DESC;

SELECT * FROM members;

